Backend/AdminPanel/Controllers/BranchController.cs
using Buisness.Abstract;
using Entities.Models;
using Entity.Params;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace AdminPanel.Controllers 
{
    public class BranchController : Controller
    {

        private readonly IBranchService _branchService;
        private readonly ILanguageService _languageService;
        private readonly IContactService _contactService;
        private readonly ITariffService _tariffService;
        private readonly IPhotosService _photosService;


        public BranchController(IBranchService branchService, ILanguageService languageService, IContactService contactService, ITariffService tariffService, IPhotosService photosService)
        {
            _branchService = branchService;
            _languageService = languageService;
            _contactService = contactService;
            _tariffService = tariffService;
            _photosService = photosService;

        }

        #region Index
        public async Task<IActionResult> Index()
        {

            var branch = await _branchService.GetAllBranchAsync();

            return View(branch);
        }

        #endregion 

        #region Create
        public async Task<IActionResult> Create(int? id)
        {

            ViewBag.Languages = await _languageService.GetAllLanguageAsync();



            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BranchParams brancParams)
        {
            ViewBag.Languages = await _languageService.GetAllLanguageAsync();

            if (!ModelState.IsValid)
            {
                return View();
            }

            var isExist = await _branchService.BranchAnyAsync(x => x.Name.ToLower() == brancParams.Name);
            if (isExist)
            {
                ModelState.AddModelError("Name", "Please change the context.Title is already exist !");
                return View();
            }         


            await _branchService.AddBranchAsync(brancParams);

            return RedirectToAction("Index");
        }
        #endregion

        #region Update
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();

            ViewBag.Languages = await _languageService.GetAllLanguageAsync();

            var branch = await _branchService.GetBranchWithIdAsync((int)id);


            if (branch == null)
                return NotFound();

            var contact = await _contactService.GetContactWithIdAsync(branch.Id);
            var tariff = await _tariffService.GetTariffWithIdAsync(branch.Id);
            var photos = await _photosService.GetPhotosWithIdAsync(branch.Id);

            if (contact == null)
                return NotFound();
            if (tariff == null)
                return NotFound();
            if (photos == null)
                return NotFound();

            BranchParams branchParams= new()
            {
                MediaSalesDepartment = contact.MediaSalesDepartment,
                WorkingHours = contact.WorkingHours,
                Description = branch.Description,
                OurAddress = contact.OurAddress,
                LanguageId = branch.LanguageId,
                TariffImage = tariff.Image,
                PhotosImage = photos.Image,
                ContactId = contact.Id,
                Phone = contact.Phone,
                Email = contact.Email,
                BranchId = branch.Id,
                TariffId = tariff.Id,
                PhotosId = photos.Id,
                Name = branch.Name,
                Map = contact.Map,
            };
            return View(branchParams);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(BranchParams branchParams, string oldPhoto)
        {
            if (!ModelState.IsValid)
            {
                return View(branchParams);
            }
            ViewBag.Languages = await _languageService.GetAllLanguageAsync();

            var isBranchUpdatedData = await _branchService.UpdateBranchAsync(branchParams, oldPhoto);

            if (isBranchUpdatedData == false)
            {
                // shekilsiz yuklemek olmaz!!!!
            }

            return RedirectToAction("Index");


        }
        #endregion

        #region Detail
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
                return NotFound();

            ViewBag.Languages = await _languageService.GetAllLanguageAsync();

            var branch = await _branchService.GetBranchWithIdAsync((int)id);


            if (branch == null)
                return NotFound();

            var contact = await _contactService.GetContactWithIdAsync(branch.Id);
            var tariff = await _tariffService.GetTariffWithIdAsync(branch.Id);
            var photos = await _photosService.GetPhotosWithIdAsync(branch.Id);

            if (contact == null)
                return NotFound();

            if (tariff == null)
                return NotFound();
             
            if (photos == null)
                return NotFound();

            BranchParams branchParams = new()
            {
                Map = contact.Map,
                Name = branch.Name,
                Email = contact.Email,
                Phone = contact.Phone,
                PhotosImage = photos.Image,
                TariffImage = tariff.Image,
                OurAddress = contact.OurAddress,
                Description = branch.Description,
                WorkingHours = contact.WorkingHours,
                LanguageName = branch.Language.Code,
                MediaSalesDepartment = contact.MediaSalesDepartment,


            };
            return View(branchParams);
        }

        [HttpGet]
        [ActionName("Delete")]

        #endregion

        #region Delete
        public async Task<IActionResult> DeleteBranch(int? id)
        {
            if (id == null)
                return NotFound();

            var movie = await _branchService.GetBranchWithIdAsync(id.Value);
            if (movie == null)
                return NotFound();


            await _branchService.DeleteBranchAsync(id.Value);

            return RedirectToAction("Index");
        }
        #endregion
    } 
}

Backend/AdminPanel/Views/Branch/Create.cshtml
@model BranchParams


@{
    ViewData["Title"] = "Create";
} 

<div class="content text-center">
    <div class="col-lg-5" style="display: inline-block">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Create Branch</h5>
            </div>

            <div class="card-body">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <form method="post" enctype="multipart/form-data" asp-action="Create" asp-controller="Branch">
                    <select name="LanguageId" id="language" class="btn btn-light">
                        @foreach (var item in ViewBag.Languages)
                        {
                            <option value="@item.Id"> @item.Code</option>

                        }
                    </select>
                    <a asp-action="Index" class="btn btn-light">
                        Go Back
                    </a>

                    <div class="form-group form-group-float">
                        <input asp-for="Name" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="Description" class="form-control" placeholder="Description">
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="OurAddress" class="form-control" placeholder="Out Address">
                        <span class="text-danger" asp-validation-for="OurAddress"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="Phone" class="form-control" placeholder="+994 50 111 11 11">
                        <span class="text-danger" asp-validation-for="Phone"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="Email" class="form-control" placeholder="Email">
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="MediaSalesDepartment" class="form-control" placeholder="Media Sales Department">
                        <span class="text-danger" asp-validation-for="MediaSalesDepartment"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="WorkingHours" class="form-control" placeholder="Working Hours">
                        <span class="text-danger" asp-validation-for="WorkingHours"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="Map" class="form-control" placeholder="Map">
                        <span class="text-danger" asp-validation-for="Map"></span>
                    </div>
                    <button type="button" class="btn btn-secondary" disabled style="width: 200px; height: 30px; margin-bottom: 10px; text-align: center">Branch Photo</button>
                    <div class="form-group form-group-float">
                        <input type="file" asp-for="PhotosPhoto" class="form-control" placeholder="Branch">
                        <span class="text-danger" asp-validation-for="PhotosPhoto"></span>
                    </div>
                    <button type="button" class="btn btn-secondary" disabled style="width: 200px; height: 30px; margin-bottom: 10px; text-align: center">Tariff Photo</button>
                    <div class="form-group form-group-float">
                        <input type="file" asp-for="TariffPhoto" class="form-control" placeholder="Tariff">
                        <span class="text-danger" asp-validation-for="TariffPhoto"></span>
                    </div>
                    <button type="submit" class="btn bg-blue-800">Submit<i class="icon-ml-2"></i></button>
                </form>
            </div>
        </div>
    </div>

</div>

Backend/AdminPanel/Views/Branch/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
    BranchParams branchParams = Model;
}

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">

            <h2 class="mt-0 header-title">Branch Details</h2>


            <div class="table-responsive">
                <form>
                    
                    <input disabled value="@branchParams.LanguageName" name="LanguageId"
                           id="language" class="btn btn-secondary" style="margin-bottom: 5px">                 

                </form>
                <table class="table table-bordered mb-0">
                    <tbody>
                        <tr>
                            <th scope="row">Name</th>
                            <td>
                                @branchParams.Name
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Description</th>
                            <td>
                                @branchParams.Description
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Our Address</th>
                            <td>
                                @branchParams.OurAddress
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Phone</th>
                            <td>
                                @branchParams.Phone
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Email</th>
                            <td>
                                @branchParams.Email
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Media Sales Department</th>
                            <td>
                                @branchParams.MediaSalesDepartment
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Working Hours</th>
                            <td>
                                @branchParams.WorkingHours
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Map</th>
                            <td>
                                <iframe src="@branchParams.Map" class="map"
                                        allowfullscreen="" loading="lazy"></iframe>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Branch Photo</th>
                            <td>
                                <div class="form-group form-group-float">
                                    <img src="/Uploads/branch/@branchParams.PhotosImage" width="250" />
                                    <input type="hidden" name="oldPhoto" value="@branchParams.PhotosPhoto" />
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Tariff Photo</th>
                            <td>
                                <div class="form-group form-group-float">
                                    <img src="/Uploads/@branchParams.TariffImage" width="250" />
                                    <input type="hidden" name="oldPhoto" value="@branchParams.TariffPhoto" />
                                </div>
                            </td>
                        </tr>


                    </tbody>
                </table>

                <a asp-action="Index" class="btn btn-secondary" style="margin-top: 5px">
                    Go Back
                </a>
            </div>
        </div>
    </div>

</div>

Backend/AdminPanel/Views/Branch/Index.cshtml
@{
    ViewData["Title"] = "Index";
    List<Branch> branches = Model;
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Branch</h4>
                <a asp-action="Create" class="btn btn-primary">Create</a>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Actions</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var branch in branches)
                            {
                                <tr>
                                    <td>
                                        @branch.Name
                                    </td>

                                    <td>
                                        <a asp-action="Detail" asp-route-id="@branch.Id" class="btn btn-info">Detail</a>
                                        <a asp-action="Update" asp-route-id="@branch.Id" class="btn btn-success">Update</a>
                                        <a asp-action="Delete" asp-route-id="@branch.Id" class="btn btn-danger" onclick="return confirm('Are you sure to delete ?')">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

Backend/AdminPanel/Views/Branch/Update.cshtml
@model BranchParams


@{
    ViewData["Title"] = "Update";
}

<div class="content text-center">
    <div class="col-lg-5" style="display: inline-block">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Create Branch</h5>
            </div>

            <div class="card-body">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <form method="post" enctype="multipart/form-data" asp-action="Update" asp-controller="Branch">
                    <input  type="hidden" asp-for="BranchId"/>
                    <input  type="hidden" asp-for="ContactId"/>
                    <input  type="hidden" asp-for="PhotosId"/>
                    <input  type="hidden" asp-for="TariffId"/>
                    <select name="LanguageId" id="language" class="btn btn-light">
                        @foreach (var item in ViewBag.Languages)
                        {
                            <option value="@item.Id"> @item.Code</option>

                        }
                    </select>
                    <a asp-action="Index" class="btn btn-light">
                        Go Back
                    </a>

                    <div class="form-group form-group-float">
                        <input asp-for="Name" value="@Model.Name" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="Description" value="@Model.Description" class="form-control" placeholder="Description">
                        <span class="text-danger" asp-validation-for="Description"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="OurAddress" value="@Model.OurAddress" class="form-control" placeholder="Out Address">
                        <span class="text-danger" asp-validation-for="OurAddress"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="Phone" value="@Model.Phone" class="form-control" placeholder="Phone">
                        <span class="text-danger" asp-validation-for="Phone"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="Email" value="@Model.Email" class="form-control" placeholder="Email">
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="MediaSalesDepartment" value="@Model.MediaSalesDepartment" class="form-control" placeholder="Media Sales Department">
                        <span class="text-danger" asp-validation-for="MediaSalesDepartment"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="WorkingHours" value="@Model.WorkingHours" class="form-control" placeholder="Working Hours">
                        <span class="text-danger" asp-validation-for="WorkingHours"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="Map" value="@Model.Map" class="form-control" placeholder="Map">
                        <span class="text-danger" asp-validation-for="Map"></span>
                    </div>
                    <button type="button" class="btn btn-secondary" disabled style="width: 200px; height: 30px; margin-bottom: 10px; text-align: center">Branch Photo</button>
                    <div class="form-group form-group-float">
                        <input type="file" asp-for="PhotosPhoto" class="form-control" placeholder="Photos">
                        <span class="text-danger" asp-validation-for="PhotosPhoto"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <img src="/Uploads/branch/@Model.PhotosImage" width="200" />
                        <input type="hidden" name="OldPhoto" value="@Model.PhotosImage" />
                    </div>
                    <button type="button" class="btn btn-secondary" disabled style="width: 200px; height: 30px; margin-bottom: 10px; text-align: center">Tariff Photo</button>
                    <div class="form-group form-group-float">
                        <input type="file" asp-for="TariffPhoto" class="form-control" placeholder="Tariff">
                        <span class="text-danger" asp-validation-for="TariffPhoto"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <img src="/Uploads/@Model.TariffImage" width="200" />
                        <input type="hidden" name="OldPhoto" value="@Model.TariffImage" />
                    </div>

                    <button type="submit" class="btn bg-blue-800">Submit<i class="icon-ml-2"></i></button>
                </form>
            </div>
        </div>
    </div>

</div>