Backend/AdminPanel/Controllers/DolbyAtmosController.cs
using Buisness.Abstract;
using DataAccess.Concret;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
 
namespace AdminPanel.Controllers
{
    public class DolbyAtmosController : Controller
    {
        private readonly IDolbyAtmosService _dolbyAtmosService;
        private readonly ILanguageService _languageService;

        public DolbyAtmosController(IDolbyAtmosService dolbyAtmosService, ILanguageService languageService)
        {
            _dolbyAtmosService = dolbyAtmosService;
            _languageService = languageService;

        }

        #region index
        public async Task<IActionResult> Index()
        {
            var dolbyAtmos = await _dolbyAtmosService.GetAllDolbyAtmosAsync();

             
            return View(dolbyAtmos);
        }
        #endregion

        #region Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Languages = await _languageService.GetAllLanguageAsync();

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DolbyAtmos dolbyAtmos)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var isExist = await _dolbyAtmosService.DolbyAtmosAnyAsync(x => x.FirstTitle.ToLower() == dolbyAtmos.FirstTitle);
            if (isExist)
            {
                ModelState.AddModelError("FirstTitle", "Please change the context.Title is already exist !");
                return View();
            }
            await _dolbyAtmosService.AddDolbyAtmosAsync(dolbyAtmos);

            return RedirectToAction("Index");
        }
        #endregion

        #region Update
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();

            var dolbyAtmos = await _dolbyAtmosService.GetDolbyAtmosWithIdAsync(id.Value);


            ViewBag.Languages = await _languageService.GetAllLanguageAsync();



            if (dolbyAtmos == null)
                return NotFound();

            return View(dolbyAtmos);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Update(DolbyAtmos dolbyAtmos)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var isExist = await _dolbyAtmosService.DolbyAtmosAnyAsync(x => x.FirstTitle.ToLower() == dolbyAtmos.FirstTitle);
            if (isExist)
            {
                ModelState.AddModelError("FirstTitle", "Please change the context.Title is already exist !");
                return View();
            }
            await _dolbyAtmosService.UpdateDolbyAtmosAsync(dolbyAtmos);

            return RedirectToAction("Index");


        }
        #endregion

        #region Detail
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
                return NotFound();

            var dolbyAtmos = await _dolbyAtmosService.GetDolbyAtmosWithIdAsync(id.Value);


            ViewBag.Languages = await _languageService.GetAllLanguageAsync();

            if (dolbyAtmos == null)
                return NotFound();

            return View(dolbyAtmos);
        }
        #endregion

        #region Delete
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteDolbyAtmos(int? id)
        {
            if (id == null)
                return NotFound();

            var dolbyAtmos = await _dolbyAtmosService.GetDolbyAtmosWithIdAsync(id.Value);
            if (dolbyAtmos == null)
                return NotFound();

            await _dolbyAtmosService.DeleteDolbyAtmosAsync(dolbyAtmos);

            return RedirectToAction("Index");
        }
        #endregion

    }

}

Backend/AdminPanel/Views/DolbyAtmos/Create.cshtml
@model DolbyAtmos
@{
    ViewData["Title"] = "Create";
}



<div class="content text-center">
    <div class="col-lg-6 ">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Create Dolby Atmos in new language</h5>

                
                   
                
            </div>
            <div class="card-body">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <form method="post" enctype="multipart/form-data" asp-action="Create" asp-controller="DolbyAtmos">

                    <select name="LanguageId" id="language" class="btn btn-light">

                        @foreach (var item in ViewBag.Languages)
                        {
                            <option value="@item.Id"> @item.Code</option>

                        }


                    </select>
                    <a asp-action="Index" class="btn btn-light">
                        Go Back
                    </a>

                    <div class="form-group form-group-float">
                        <input asp-for="FirstTitle" class="form-control" placeholder="First Title">
                        <span class="text-danger" asp-validation-for="FirstTitle"></span>
                    </div>
                    <div class="form-group">
                        <textarea asp-for="FirstDescription" rows="4" cols="4" class="form-control" placeholder="First Description"></textarea>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="YoutubeURL" class="form-control" placeholder="Youtube Url">
                        <span class="text-danger" asp-validation-for="YoutubeURL"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="SecondTitle" class="form-control" placeholder="Second Title">
                        <span class="text-danger" asp-validation-for="SecondTitle"></span>
                    </div>
                    <div class="form-group">
                        <textarea asp-for="SecondDescription" rows="4" cols="4" class="form-control" placeholder="Second Description"></textarea>
                    </div>


                    <button type="submit" class="btn bg-blue-800">Submit<i class="icon-ml-2"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>

Backend/AdminPanel/Views/DolbyAtmos/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
    DolbyAtmos dolbyAtmos = Model;
}


<div class="col-lg-12">
    <div class="card">
        <div class="card-body">

            <h2 class="mt-0 header-title">DolbyAtmos Details</h2>


            <div class="table-responsive">
                <form>
                    <select name="LanguageId" id="language" class="btn btn-secondary" style="margin-bottom: 5px">

                        @foreach (var item in ViewBag.Languages) 
                        {

                            <!option value="@item.Id" @(item.Id == Model.LanguageId ? "selected" : "")> @item.Code</!option>

                        }


                    </select>

                </form>
                <table class="table table-bordered mb-0">

                    <tbody>
                        <tr>
                            <th class="col-md-6">
                                FirstTitle & FirstDescription
                            </th>
                            <td>
                                <div data-toggle="modal" data-target="#exampleModalLong" style="cursor: pointer">
                                    @dolbyAtmos.FirstTitle


                                </div>
                                <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLongTitle">Description</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body" style="background-color: midnightblue; color: white">

                                                @dolbyAtmos.FirstDescription

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>

                        </tr>
                        <tr>
                            <th class="col-md-6">
                                SecondTitle & SecondDescription
                            </th>
                            <td>
                                <div data-toggle="modal" data-target="#exampleModalLongDesc" style="cursor: pointer">
                                    @dolbyAtmos.SecondTitle
                                </div>
                                <div class="modal fade" id="exampleModalLongDesc" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLongDesc">Second Description</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body" style="background-color: midnightblue; color: white">

                                                @dolbyAtmos.SecondDescription

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>

                        </tr>

                    </tbody>
                </table>

                <a asp-action="Index" class="btn btn-secondary" style="margin-top: 5px">
                    Go Back
                </a>
            </div>
        </div>
    </div>
</div>

Backend/AdminPanel/Views/DolbyAtmos/Index.cshtml
@{
    ViewData["Title"] = "Index";
    List<DolbyAtmos> dolbyAtmos = Model;
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Dolby Atmos</h4>
                <a asp-action="Create" class="btn btn-primary">Create</a>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Actions</th>
                             
                            </tr>
                        </thead>
                        <tbody>
                       
                            @foreach (var dolby in dolbyAtmos)
                            {
                                <tr>
                                    <td>
                                        @dolby.FirstTitle
                                    </td>

                                    <td>                                

                                        <a asp-action="Detail" asp-route-id="@dolby.Id" class="btn btn-info">Detail</a>
                                        <a asp-action="Update" asp-route-id="@dolby.Id" class="btn btn-success">Update</a> 
                                        <a asp-action="Delete" asp-route-id="@dolby.Id" onclick="return confirm('Are you sure to delete ?')" class="btn btn-danger">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

Backend/AdminPanel/Views/DolbyAtmos/Update.cshtml
@model DolbyAtmos
@{
    ViewData["Title"] = "Update";
}



<div class="content text-center">
    <div class="col-lg-6 ">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Update Dolby Atmos in new language</h5>




            </div>
            <div class="card-body">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <form method="post" enctype="multipart/form-data" asp-action="Create" asp-controller="DolbyAtmos">

                    <select name="LanguageId" id="language" class="btn btn-light">

                        @foreach (var item in ViewBag.Languages)
                        {
                            <!option value="@item.Id" @(item.Id == Model.LanguageId ? "selected" : "")> @item.Code</!option>
                        }


                    </select>
                    <a asp-action="Index" class="btn btn-light">
                        Go Back
                    </a>

                    <div class="form-group form-group-float">
                        <input asp-for="FirstTitle" class="form-control" placeholder="First Title">
                        <span class="text-danger" asp-validation-for="FirstTitle"></span>
                    </div>
                    <div class="form-group">
                        <textarea asp-for="FirstDescription" rows="4" cols="4" class="form-control" placeholder="First Description"></textarea>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="YoutubeURL" class="form-control" placeholder="Youtube Url">
                        <span class="text-danger" asp-validation-for="YoutubeURL"></span>
                    </div>
                    <div class="form-group form-group-float">
                        <input asp-for="SecondTitle" class="form-control" placeholder="Second Title">
                        <span class="text-danger" asp-validation-for="SecondTitle"></span>
                    </div>
                    <div class="form-group">
                        <textarea asp-for="SecondDescription" rows="4" cols="4" class="form-control" placeholder="Second Description"></textarea>
                    </div>


                    <button type="submit" class="btn bg-blue-800">Submit<i class="icon-ml-2"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>